repos:
    - repo: local
      hooks:
          - id: rustfmt
            name: Run `rustfmt`
            language: rust
            types: [rust]
            entry: cargo +nightly fmt --all -- --check
            pass_filenames: false
            stages: [pre-commit]
          - id: clippy
            name: Run cargo clippy
            types: [rust]
            language: rust
            entry: cargo +stable clippy -p rwasm-machine -p rwasm-executor -p rwasm-machine-test -- -D warnings
            pass_filenames: false
            stages: [pre-commit]