use crate::operations::{LE16bCols, Range16bCols, Range32bCols};
use rwasm::{
    mem_index::{FUNC_FRAME_END, FUNC_FRAME_START, SP_END, TABLE_SEG_END, TABLE_SEG_START},
    N_MAX_ELEM_SEGMENTS_BITS, N_MAX_TABLE_SIZE,
};
use rwasm_executor::SP_START;

pub type StackAddressCols<T> = Range16bCols<T, SP_END, SP_START>;

pub type TableAddressCols<T> = LE16bCols<T, N_MAX_TABLE_SIZE>;
pub type CallStackAddressCols<T> = Range16bCols<T, FUNC_FRAME_START, FUNC_FRAME_END>;

const N_MAX_ELEM_SEGMENTS_BITS_U32: u32 = N_MAX_ELEM_SEGMENTS_BITS as u32;
pub type ElementAddressCols<T> = Range16bCols<T, 0, N_MAX_ELEM_SEGMENTS_BITS_U32>;
const TABLE_ADDR_START_SHIFTED: u32 = (TABLE_SEG_END - TABLE_SEG_START) >> 16;
const TABLE_ADDR_END_SHIFTED: u32 = (TABLE_SEG_END - TABLE_SEG_START) as u16 as u32;
const TABLE_ADDR_START_HI16_SHIFED: u32 = TABLE_ADDR_START_SHIFTED >> 16;
const TABLE_ADDR_START_LOW16_SHIFTED: u32 = TABLE_ADDR_START_SHIFTED as u16 as u32;
const TABLE_ADDR_END_HI16_SHIFTED: u32 = TABLE_ADDR_END_SHIFTED >> 16;
const TABLE_ADDR_END_LOW16_SHIFTED: u32 = TABLE_ADDR_END_SHIFTED as u16 as u32;

pub type TableAccessCol<T> = Range32bCols<
    T,
    TABLE_SEG_START,
    TABLE_SEG_END,
    TABLE_ADDR_START_HI16_SHIFED,
    TABLE_ADDR_END_HI16_SHIFTED,
    TABLE_ADDR_START_LOW16_SHIFTED,
    TABLE_ADDR_END_LOW16_SHIFTED,
>;
