use crate::operations::{Range16bCols, Range32bCols};
use rwasm::{
    mem_index::{
        FUNC_FRAME_END, FUNC_FRAME_START, GLOBAL_MEM_END, GLOBAL_MEM_START, SP_END, TABLE_SEG_END,
        TABLE_SEG_START,
    },
    N_MAX_ELEM_SEGMENTS_BITS, N_MAX_TABLE_SIZE,
};
use rwasm_executor::SP_START;

pub type StackAddressCols<T> = Range16bCols<T, SP_END, SP_START>;

pub type TableAddressCols<T> = Range16bCols<T, 0, N_MAX_TABLE_SIZE>;

pub type CallStackAddressCols<T> = Range16bCols<T, FUNC_FRAME_START, FUNC_FRAME_END>;

const N_MAX_ELEM_SEGMENTS_BITS_U32: u32 = N_MAX_ELEM_SEGMENTS_BITS as u32;
pub type ElementAddressCols<T> = Range16bCols<T, 0, N_MAX_ELEM_SEGMENTS_BITS_U32>;
const TABLE_ADDR_START_SHIFTED: u32 = 0;
const TABLE_ADDR_END_SHIFTED: u32 = TABLE_SEG_END - TABLE_SEG_START;
const TABLE_ADDR_START_HI16_SHIFED: u32 = TABLE_ADDR_START_SHIFTED >> 16;
const TABLE_ADDR_START_LOW16_SHIFTED: u32 = TABLE_ADDR_START_SHIFTED as u16 as u32;
const TABLE_ADDR_END_HI16_SHIFTED: u32 = TABLE_ADDR_END_SHIFTED >> 16;
const TABLE_ADDR_END_LOW16_SHIFTED: u32 = TABLE_ADDR_END_SHIFTED as u16 as u32;

pub type TableAccessCol<T> = Range32bCols<
    T,
    TABLE_SEG_START,
    TABLE_SEG_END,
    TABLE_ADDR_START_HI16_SHIFED,
    TABLE_ADDR_END_HI16_SHIFTED,
    TABLE_ADDR_START_LOW16_SHIFTED,
    TABLE_ADDR_END_LOW16_SHIFTED,
>;

const MEM_ADDR_END: u32 = GLOBAL_MEM_END - GLOBAL_MEM_START;

const MEM_ADDR_END_HI16_SHIFTED: u32 = MEM_ADDR_END >> 16;
const MEM_ADDR_END_LOW16_SHIFTED: u32 = MEM_ADDR_END as u16 as u32;

pub type GlobalMemoryCol<T> =
    Range32bCols<T, 0, MEM_ADDR_END, 0, MEM_ADDR_END_HI16_SHIFTED, 0, MEM_ADDR_END_LOW16_SHIFTED>;
